[package]
name = "viewer"
version = "0.1.0"
authors = ["Paul Lesur <paul.lesur@dfki.de>"]

[dependencies]
kiss3d = "0.19"
nalgebra = "0.18"
alga = "0.9.0"
log = "0.4.6"
env_logger = "0.6.1"

[dependencies.nom]
version = "4.2.3"
features = ["regexp"]
